validate

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,7 +2,7 @@ name: ci
 
 on:
   schedule:
-    - cron: '0 10 * * *' # everyday at 10am
+    - cron: '0 10 * * *'
   push:
     branches:
       - 'master'
@@ -10,9 +10,6 @@ on:
     tags:
       - 'v*'
   pull_request:
-    branches:
-      - 'master'
-      - 'releases/v*'
 
 jobs:
   main:
@@ -35,16 +32,11 @@ jobs:
         with:
           version: ${{ matrix.buildx-version }}
       -
-        name: Inspect builder
+        name: Nodes output
         run: |
-          echo "Name:      ${{ steps.buildx.outputs.name }}"
-          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
-          echo "Status:    ${{ steps.buildx.outputs.status }}"
-          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
-          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
-      -
-        name: Dump context
-        uses: crazy-max/ghaction-dump-context@v2
+          cat << EOF
+          ${{ steps.buildx.outputs.nodes }}
+          EOF
 
   multi:
     runs-on: ubuntu-latest
@@ -54,28 +46,11 @@ jobs:
         uses: actions/checkout@v3
       -
         name: Set up Docker Buildx 1
-        id: buildx1
         uses: ./
-      -
-        name: Inspect builder 1
-        run: |
-          echo "Name:      ${{ steps.buildx1.outputs.name }}"
-          echo "Endpoint:  ${{ steps.buildx1.outputs.endpoint }}"
-          echo "Status:    ${{ steps.buildx1.outputs.status }}"
-          echo "Flags:     ${{ steps.buildx1.outputs.flags }}"
-          echo "Platforms: ${{ steps.buildx1.outputs.platforms }}"
       -
         name: Set up Docker Buildx 2
-        id: buildx2
         uses: ./
-      -
-        name: Inspect builder 2
-        run: |
-          echo "Name:      ${{ steps.buildx2.outputs.name }}"
-          echo "Endpoint:  ${{ steps.buildx2.outputs.endpoint }}"
-          echo "Status:    ${{ steps.buildx2.outputs.status }}"
-          echo "Flags:     ${{ steps.buildx2.outputs.flags }}"
-          echo "Platforms: ${{ steps.buildx2.outputs.platforms }}"
+
   error:
     runs-on: ubuntu-latest
     steps:
@@ -147,6 +122,7 @@ jobs:
         name: Check cmd
         run: |
           docker build --help
+
   use:
     runs-on: ubuntu-latest
     strategy:
@@ -208,6 +184,7 @@ jobs:
           docker buildx inspect
           docker buildx inspect | grep Driver | grep docker
           docker buildx inspect | grep Status | grep running
+
   endpoint:
     runs-on: ubuntu-latest
     services:
@@ -330,13 +307,9 @@ jobs:
         with:
           version: ${{ matrix.buildx-version }}
       -
-        name: Inspect builder
-        run: |
-          echo "Name:      ${{ steps.buildx.outputs.name }}"
-          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
-          echo "Status:    ${{ steps.buildx.outputs.status }}"
-          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
-          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
+        name: List builder platforms
+        run: echo ${{ steps.buildx.outputs.platforms }}
+
   build-ref:
     runs-on: ubuntu-latest
     strategy:
@@ -357,9 +330,30 @@ jobs:
         with:
           version: https://github.com/docker/buildx.git#${{ matrix.ref }}
       -
-        name: Check version
+        name: Create Dockerfile
         run: |
-          docker buildx version
+          cat > ./Dockerfile <<EOL
+          FROM alpine
+          EOL
+      -
+        name: Build
+        uses: docker/build-push-action@master
+        with:
+          context: .
+
+  standalone-cmd:
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v3
+      -
+        name: Uninstall docker cli
+        run: |
+          sudo apt-get purge -y moby-cli moby-buildx
+      -
+        name: Set up Docker Buildx
+        uses: ./
       -
         name: Create Dockerfile
         run: |
@@ -368,6 +362,139 @@ jobs:
           EOL
       -
         name: Build
-        uses: docker/build-push-action@v4
+        run: |
+          buildx build .
+
+  standalone-action:
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v3
+      -
+        name: Uninstall docker cli
+        run: |
+          sudo apt-get purge -y moby-cli moby-buildx
+      -
+        name: Set up Docker Buildx
+        uses: ./
+        with:
+          version: ${{ matrix.buildx-version }}
+      -
+        name: Create Dockerfile
+        run: |
+          cat > ./Dockerfile <<EOL
+          FROM alpine
+          EOL
+      -
+        name: Build
+        uses: docker/build-push-action@master
         with:
           context: .
+
+  standalone-install-error:
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v3
+      -
+        name: Uninstall docker cli
+        run: |
+          sudo apt-get purge -y moby-cli moby-buildx
+      -
+        name: Set up Docker Buildx
+        id: buildx
+        continue-on-error: true
+        uses: ./
+        with:
+          install: true
+      -
+        name: Check
+        run: |
+          echo "${{ toJson(steps.buildx) }}"
+          if [ "${{ steps.buildx.outcome }}" != "failure" ] || [ "${{ steps.buildx.conclusion }}" != "success" ]; then
+            echo "::error::Should have failed"
+            exit 1
+          fi
+
+  append:
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v3
+      -
+        name: Create dummy contexts
+        run: |
+          docker context create ctxbuilder2
+          docker context create ctxbuilder3
+      -
+        name: Set up Docker Buildx
+        id: buildx
+        uses: ./
+        with:
+          append: |
+            - name: builder2
+              endpoint: ctxbuilder2
+              platforms: linux/amd64
+              driver-opts:
+                - image=moby/buildkit:master
+                - network=host
+            - endpoint: ctxbuilder3
+              platforms: linux/arm64
+      -
+        name: List builder platforms
+        run: echo ${{ steps.buildx.outputs.platforms }}
+
+  platforms:
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v3
+      -
+        name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+      -
+        name: Set up Docker Buildx
+        uses: ./
+        with:
+          platforms: linux/amd64
+
+  docker-context:
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v3
+      -
+        name: Create Docker context
+        run: |
+          docker context create foo
+          docker context use foo
+      -
+        name: Set up Docker Buildx
+        uses: ./
+        with:
+          driver: docker
+
+  cleanup:
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        cleanup:
+          - true
+          - false
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v3
+      -
+        name: Set up Docker Buildx
+        uses: ./
+        with:
+          cleanup: ${{ matrix.cleanup }}
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v3
